services:

  db:
    image: 'postgres:16.2'
    container_name: service-tasks-db
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: service-tasks
      POSTGRES_USER: service-tasks-owner
      POSTGRES_PASSWORD: service-tasks-owner
